### ISSUE TITLE
Erreur avec la connexion à la BD

### ISSUE THREAD

**Issue by samuelbeaulieu** [TheJackMachine/php-docker#5]
### Problème
![Screen Shot 2020-11-28 at 8 36 55 PM](https://user-images.githubusercontent.com/64789082/100529962-6437f900-31ba-11eb-818f-46012ea732a8.png)

La connexion à la BD ne se fait pas sans devoir modifié le `'host' => 'localhost'` pour `'host' => 'mysql'` dans l'array `mysql`.

![Screen Shot 2020-11-28 at 8 42 32 PM](https://user-images.githubusercontent.com/64789082/100529947-3f438600-31ba-11eb-826f-e586a147a55d.png)

Est-ce normal? Idéalement on ne toucherais pas à cette valeur selon moi. J'ai tenté de modifié plus trucs sans succès.

Pour l'instant, je vais modifier cette valeur manuellement, c'est pas plus pire que de modifier `database`, `username` ou `password`.

Si tu connais une façon bypass cette modification manuelle, je serais très curieux de la connaître!

**Comment by TheJackMachine** [comment]
C’est normal.

En fait c’est même le principal intérêt.

Sur la plupart des serveurs on utilise localhost car l’ensemble des services roulent sur le même environnement.
On pourrait faire pareil avec docker en intégrant Mysql au conteneur php, ce n’est pas ce que j’ai souhaité faire ici par conception afin entre autre de ne pas surcharger le conteneur PHP.

Le fait d’avoir mysql sur un conteneur différent le fait apparaître comme s’il était sur une autre machine du réseau ce qui se rapproche de l’architecture qu’on pourrait souhaiter avoir sur ... un cloud par exemple.
L’autre avantage et qu’on peut changer de type de BD si on le souhaite, par exemple Postgres, sans devoir forcement avoir la BD Mysql d’allumée.
Dans le config October, ça se fait en plus très simplement en créant, dans le dossier DEV, un autre fichier de configuration de BD en changeant le clefs.
On pourrait aussi utiliser carrément le fichier d’environnement pour injecter les bonnes valeurs.
Je ne l’ai jamais utilisé, préférant le fichier de config du dossier DEV, mais ça peut aussi être extrêmement pratique dans la mesure où les données de la BD ( login, pass ) ne seraient pas gittées.

Voir : 
https://octobercms.com/docs/setup/configuration#environment-config

**Comment by samuelbeaulieu** [comment]
Super bonne explication! J'avais pas vu ça comme ça. Pour moi, s'était plus un step back puisqu'on devait modifier un truc de plus comparer à ma config php en local d'avant. C'est une super bonne façon de faire, bravo!
